### PR TITLE
Feature/v73 post release jfs

### PR DESCRIPTION
**Pull request by SolomonShorser-OICR**
@jweiser Do you know why this code is still on a separate Release 73-specific branch? There's no merge conflicts & it looks like it should have been merged back in a while ago.

### CODE REVIEW

**Comment by jweiser** [comment]
> @jweiser Do you know why this code is still on a separate Release 73-specific branch? There's no merge conflicts & it looks like it should have been merged back in a while ago.

@SolomonShorser-OICR I think Justin and I were working on running the post-release steps together manually and we ran into some issues.  I was addressing these, but I don't think I got to a stage where it was ready to use Jenkins.  There are some tweaks that need to be made to reflect updates to the post-steps, so I will need to make new changes to this PR before it should be merged.

**Comment by SolomonShorser-OICR** [comment]
Oh. I didn't know that you "ran into issues".... I've been running the post-Release steps from Jenkins and so far they have all worked fine.

**Comment by jweiser** [comment]
Overall it is okay, but a few changes need to be made since the code was created.  I can make the updates here or we can do it as a new PR.

**Comment by jweiser** [comment]
> @jweiser Any updates on this?

@SolomonShorser-OICR Overall it is okay, but a few changes need to be made since the code was created.  I can make the updates here or we can do it as a new PR.

**Comment by SolomonShorser-OICR** [comment]
Well... if we merge this, will we be able to use this code _as-is_, or will we need to use a new branch with the changes you're talking about?

**Comment by jweiser** [comment]
> Well... if we merge this, will we be able to use this code _as-is_, or will we need to use a new branch with the changes you're talking about?

No, some changes are needed in the data-exporter file for it to run properly.

**Comment by SolomonShorser-OICR** [comment]
Ok but that's a separate repository, right? I'd suggest that if no further changes are needed in _this_ repository, we merge this PR and your changes can be on a new branch in the data-exporter repository.

**Comment by jweiser** [comment]
No, sorry I should have been more precise - the change needed is to the file in this repository that runs data-exporter.

**Comment by SolomonShorser-OICR** [comment]
Ah ok. Then in that case, it's probably better to leave this PR open until all changes needed to run it are complete. Otherwise, we'll just be running off a _different_ branch for Release 77.

**Comment by SolomonShorser-OICR** [comment]
@jweiser Actually... would it be possible to move the code that runs data-exporter to the repository that _contains_ data exporter? That was all the code could be in one place and this PR could be closed, and the new code could be on a branch in another repository. Would that work?

**Review by adamjohnwright — APPROVED** [review]

**Pull request merged**
